apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    owner: xxhf
    env: dev
spec:
  containers:
  - image: nginx:1.23.1 
    name: nginx 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
