apiVersion: v1
kind: ResourceQuota
metadata:
  name: high-qos-limit-requests 
  namespace: default
spec:
  hard:
    limits.cpu: 8 
    limits.memory: 24Gi
    pods: "10"
    requests.cpu: 4
    requests.memory: 12Gi
  scopes:
  - NotBestEffort
