apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website 
spec:
  containers:
  - name: wp-pod 
    image: wordpress:6
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    env:
      - name: WORDPRESS_DB_HOST 
        valueFrom:
          configMapKeyRef:
            name: wp-cm 
            key: WORDPRESS_DB_HOST 
      - name: WORDPRESS_DB_USER 
        valueFrom:
          configMapKeyRef:
            name: wp-cm 
            key: WORDPRESS_DB_USER 
      - name: WORDPRESS_DB_PASSWORD 
        valueFrom:
          configMapKeyRef:
            name: wp-cm 
            key: WORDPRESS_DB_PASSWORD 
      - name: WORDPRESS_DB_NAME 
        valueFrom:
          configMapKeyRef:
            name: wp-cm 
            key: WORDPRESS_DB_NAME 
