apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: wordpress
    role: database
spec:
  containers:
  - name: wp-mysql 
    image: mysql:5.7 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    envFrom:
    - prefix: 'MYSQL_'
      configMapRef:
        name: mysql-cm

