apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website 
spec:
  containers:
  - name: wp-pod 
    image: wordpress:6 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80 
    envFrom:
    - prefix: 'WORDPRESS_DB_'
      configMapRef:
        name: wp-cm

