apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm 
data:
  DATABASE: 'db_wordpress'
  USER: 'wordpress'
  PASSWORD: '123456'
  ROOT_PASSWORD: '123456'
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: wordpress
    role: database
spec:
  containers:
  - name: wp-mysql 
    image: mysql:5.7 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    envFrom:
    - prefix: 'MYSQL_'
      configMapRef:
        name: mysql-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm 
data:
  HOST: '100.100.239.19'
  USER: 'wordpress'
  PASSWORD: '123456'
  NAME: 'db_wordpress'
---
apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website 
spec:
  containers:
  - name: wp-pod 
    image: wordpress:6 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80 
    envFrom:
    - prefix: 'WORDPRESS_DB_'
      configMapRef:
        name: wp-cm

