apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dynamic-pvc
spec:
  storageClassName: nfs-client-deleted 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
