apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-dep-res-q2
  name: ngx-dep-res-q2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-dep-res-q2
  template:
    metadata:
      labels:
        app: ngx-dep-res-q2
    spec:
      containers:
      - image: nginx:1.22.1
        name: nginx
        resources:
          limits:
            cpu: 200m 
            memory: 100Mi
          requests:
            cpu: 100m 
            memory: 50Mi
