apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-dep-res
  name: ngx-dep-res
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-dep-res
  template:
    metadata:
      labels:
        app: ngx-dep-res
    spec:
      containers:
      - image: nginx:1.22.1
        name: nginx
        resources:
          limits:
            cpu: 2 
            memory: 100Mi
          requests:
            cpu: 2 
            memory: 50Mi
