global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.25.3-debian-11-r1
  digest: ""

replicaCount: 1

containerPorts:
  http: 8080
  https: ""

resources:
  ## Example:
   limits:
      cpu: 100m
      memory: 128Mi
  ## Examples:
   requests:
      cpu: 100m
      memory: 128Mi

