apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app-dep
  labels:
    app: http-app-dep
  annotations:
    kubernetes.io/change-cause: version=v4 
spec:
  minReadySeconds: 30 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 10
  replicas: 4
  selector:
    matchLabels:
      app: http-app-dep
  template:
    metadata:
      labels:
        app: http-app-dep
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/xxhf/http-app:v4
        name: http-app 
