apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-dep-prob
  name: ngx-dep-prob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-dep-prob
  template:
    metadata:
      labels:
        app: ngx-dep-prob
    spec:
      volumes:
      - name: ngx-conf-vol
        configMap:
          name: ngx-conf
      containers:
      - image: nginx:1.22.1
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: ngx-conf-vol
        startupProbe:
          periodSeconds: 1
          exec:
            command: ["cat", "/var/run/nginx.pid"] 
        livenessProbe:
          periodSeconds: 10
          tcpSocket:
            port: 80
        readinessProbe:
          periodSeconds: 5 
          httpGet:
            path: /ready
            port: 80
