apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker
  labels:
    owner: xxhf
    env: dev
spec:
  containers:
  - image: busybox 
    name: nginx 
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeName: worker-01
