apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset 
  labels:
    app: nginx-reps 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-reps 
  template:
    metadata:
      labels:
        app: nginx-reps 
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1 

