apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    env: dev
    app: nginx
spec:
  volumes:
  - name: nginx-vol
    configMap:
      name: nginx-conf 
  containers:
  - name: nginx-pod 
    image: nginx:1.22.1 
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/nginx/conf.d 
      name: nginx-vol
