apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;

      location / {
          default_type text/plain;
          return 200
          'srv : $server_addr:$server_port\nhost: $hostname\nuri : $request_method $host $request_uri\ndate: $time_iso8601\n';
      }

      location /ping {
        return 200 "pongggggggggggggggggggggggggg";
      }
    }
