apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-100m-pv

spec:
  storageClassName: host-test
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/host-100m-pv/
